version: 0.0
os: linux
files:
  - source: /
    destination: /home/project
hooks:
   BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 60
      runas: root
    ApplicationStart:
    - location: hooks/start_server.sh
      timeout: 30
      runas: root
